services:
  - type: web
    name: your-institute
    env: docker
    plan: free
    repo: https://github.com/MunirN28/Your-Institute
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
